### ISSUE TITLE
Agent Issue

### ISSUE THREAD

**Issue by ma-karai** [Inlustra/auto-docker-dash#39]
Hey Ho, Still digging this project. I tried to set up an agent via ENV var and i am gettin this error

` error:   ┗ [1] { component: 'agent', error: 'Only absolute URLs are supported' }`

docker compose

```
 plugsy-agent:
    container_name: plugsy-agent
    image: plugsy/agent
    environment:
      - PLUGSY_AGENT_ENDPOINT="http://192.168.0.40:3000/graphql"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
