### ISSUE TITLE
Can we get some theme overrides love for Global things? 

### ISSUE THREAD

**Issue by airtonix** [Inlustra/auto-docker-dash#47]
https://github.com/plugsy/core/blob/5a927a413747dc1d4d2323f5a458549f1186b0fb/packages/core/pages/_document.tsx#L25

Currently we can't affect the layout of anything above the `AppContainer`.

I want to put : 

```css
html, body {
    display: flex;
    flex-direction: column;
    height: 100%;
    width: 100%;
}
.Home__AppContainer-sc-6nia8d-4.ctHsFZ {
    display: flex;
    flex-direction: column;
    flex-grow: 1;
    align-items: start;
    justify-content: start;
}
.Home__HomeContainer-sc-6nia8d-0.jHWNLW {
    margin: 0 auto;
}

```
So i can get rid of the white background that shows up below the `AppContainer` when using the Dracula theme.

--- 
If our theme object can have something that can be dumped in the link above then themers can fill that gap on their end : 

```
{
    "$schema": "https://github.com/plugsy/core/releases/download/v7.0.0/core-config-schema.json",
    "theme": {
        "components": {

            "Global": {
                "html, body": {
                    "display": "flex",
                    "flexDirection": "column",
                    "height": "100%",
                    "width": "100%"
                }
            }

        }
    }
}
```
